name: Publish Docker images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          # 'ai-service',
          # 'makeline-service',
          # 'order-service',
          'product-service',
          # 'store-admin',
          # 'store-front',
          # 'virtual-customer',
          # 'virtual-worker'
        ]
    # permissions:
    #   packages: write
    #   contents: read
    #   attestations: write
    #   id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: 'Print secrets.DOCKER_USERNAME'
        shell: bash
        # env:
        #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: echo "${{ secrets.DOCKER_USERNAME }}"

      - name: 'Print secrets.DOCKERHUB_PASSWORD'
        shell: bash
        # env:
        #   DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./src/${{ matrix.service }}
          file: ./src/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
